#!/usr/bin/env python3
"""Pack assembled little-endian microcode into MachXO2 512x18 EBRs.

Each INITVAL contains sixteen 18-bit locations in 20-bit slots. PDPW8KC
swaps its two 9-bit output halves; the generated wiring restores word order.
The generated Verilog is a build product, not a microcode source.
"""
import argparse
from pathlib import Path
import struct


def generate(binary, words):
    if words < 512 or words > 3584 or words % 512:
        raise ValueError("HC1200 uROM size must be 512..3584 words in 512-word banks")
    if len(binary) % 2 or len(binary) > words * 2:
        raise ValueError("microcode must contain whole 16-bit words and fit the uROM")
    image = list(struct.unpack(f"<{len(binary) // 2}H", binary))
    image += [0x00b0] * (words - len(image))  # native 'b *' in unused locations
    banks = words // 512
    lines = [
        "// Generated by ucode/make_urom_ebr.py; do not edit or commit.",
        "`timescale 1ns/1ps",
        f"module j11_urom_ebr #(parameter integer WORDS = {words}) (",
        "    input wire clk, rst, enable,",
        "    input wire [11:0] address,",
        "    output reg [15:0] data",
        ");",
        f"    if (WORDS != {words}) begin : image_size_mismatch",
        "        J11_UROM_IMAGE_SIZE_MISMATCH regenerate_image();",
        "    end",
        "    reg [2:0] bank;",
        "    always @(posedge clk)",
        "        if (rst) bank <= 0;",
        "        else if (enable) bank <= address[11:9];",
        "    // synthesis translate_off",
        "    GSR GSR_INST (.GSR(1'b1));",
        "    PUR PUR_INST (.PUR(1'b1));",
        "    // synthesis translate_on",
    ]
    for bank in range(banks):
        lines += [f"    wire [17:0] raw_{bank};", "    PDPW8KC #(",
                  '        .DATA_WIDTH_W(18), .DATA_WIDTH_R(18), .REGMODE("NOREG"),',
                  '        .GSR("DISABLED"), .RESETMODE("SYNC"),',
                  '        .CSDECODE_W("0b000"), .CSDECODE_R("0b000"),']
        for row in range(32):
            start = bank * 512 + row * 16
            init = sum(value << (20 * n) for n, value in enumerate(image[start:start + 16]))
            comma = "," if row < 31 else ""
            lines.append(f'        .INITVAL_{row:02X}("0x{init:080X}"){comma}')
        lines.append(f"    ) bank_{bank} (")
        ports = [f".DI{bit}(1'b0)" for bit in range(18)]
        ports += [f".ADW{bit}(1'b0)" for bit in range(9)]
        ports += [".BE0(1'b0)", ".BE1(1'b0)", ".CEW(1'b0)", ".CLKW(clk)",
                  ".CSW0(1'b0)", ".CSW1(1'b0)", ".CSW2(1'b0)"]
        ports += [f".ADR{bit}(address[{bit - 4}])" if bit >= 4 else
                  f".ADR{bit}(1'b0)" for bit in range(13)]
        ports += [".CER(enable)", ".OCER(1'b1)", ".CLKR(clk)", ".RST(rst)",
                  ".CSR0(1'b0)", ".CSR1(1'b0)", ".CSR2(1'b0)"]
        ports += [f".DO{bit}(raw_{bank}[{bit}])" for bit in range(18)]
        lines.append("        " + ",\n        ".join(ports))
        lines.append("    );")
    lines += ["    always @* begin", "        case (bank)"]
    for bank in range(banks):
        lines.append(f"        3'd{bank}: data = {{raw_{bank}[6:0], raw_{bank}[17:9]}};")
    lines += ["        default: data = 16'h00b0;",
              "        endcase", "    end", "endmodule", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("binary", type=Path)
    parser.add_argument("--words", type=int, required=True)
    args = parser.parse_args()
    try:
        print(generate(args.binary.read_bytes(), args.words), end="")
    except (OSError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
