#!/usr/bin/env python3
"""Pack microcode and a reserved 64-word context into MachXO2 512x18 EBRs.

Each INITVAL contains sixteen 18-bit locations in 20-bit slots. PDPW8KC
swaps its two 9-bit output halves; the generated wiring restores word order.
The generated Verilog is a build product, not a microcode source.
"""
import argparse
import re
from pathlib import Path
import struct

CONTEXT_WORDS = 64


def make_image(binary, words):
    if words < 512 or words > 3584 or words % 512:
        raise ValueError("HC1200 uROM size must be 512..3584 words in 512-word banks")
    code_words = words - CONTEXT_WORDS
    if len(binary) % 2 or len(binary) > code_words * 2:
        raise ValueError(f"microcode must contain whole 16-bit words and fit in "
                         f"{code_words} words ({CONTEXT_WORDS} reserved for context)")
    image = list(struct.unpack(f"<{len(binary) // 2}H", binary))
    image += [0x00b0] * (code_words - len(image))  # native 'b *' in unused code
    return image + [0] * CONTEXT_WORDS


def generate_mem(binary, words):
    image = make_image(binary, words)
    return "@0000\n" + "".join(
        " ".join(f"{value:04x}" for value in image[start:start + 16]) + "\n"
        for start in range(0, words, 16))


def generate(binary, words, module_name="j11_urom_ebr"):
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", module_name):
        raise ValueError("invalid Verilog module name")
    image = make_image(binary, words)
    banks = words // 512
    lines = [
        "// Generated by ucode/make_urom_ebr.py; do not edit or commit.",
        "`timescale 1ns/1ps",
        f"module {module_name} #(parameter integer WORDS = {words}) (",
        "    input wire clk, rst, enable,",
        "    input wire [11:0] address,",
        "    input wire write_enable,",
        "    input wire [5:0] write_address,",
        "    input wire [15:0] write_data,",
        "    output reg [15:0] data",
        ");",
        f"    if (WORDS != {words}) begin : image_size_mismatch",
        "        J11_UROM_IMAGE_SIZE_MISMATCH regenerate_image();",
        "    end",
        "    reg [2:0] bank;",
        "    always @(posedge clk)",
        "        if (rst) bank <= 0;",
        "        else if (enable) bank <= address[11:9];",
        "    // synthesis translate_off",
        "    GSR GSR_INST (.GSR(1'b1));",
        "    PUR PUR_INST (.PUR(1'b1));",
        "    // synthesis translate_on",
    ]
    for bank in range(banks):
        lines += [f"    wire [17:0] raw_{bank};", "    PDPW8KC #(",
                  '        .DATA_WIDTH_W(18), .DATA_WIDTH_R(18), .REGMODE("NOREG"),',
                  '        .GSR("DISABLED"), .RESETMODE("SYNC"),',
                  '        .CSDECODE_W("0b000"), .CSDECODE_R("0b000"),']
        for row in range(32):
            start = bank * 512 + row * 16
            init = sum(value << (20 * n) for n, value in enumerate(image[start:start + 16]))
            comma = "," if row < 31 else ""
            lines.append(f'        .INITVAL_{row:02X}("0x{init:080X}"){comma}')
        if bank == banks - 1:
            lines.append("    ) context_ebr (")
            # Only the final 64 words are writable. Both byte enables are
            # asserted; unlike the read outputs, DI bits are not swapped.
            ports = [f".DI{bit}(write_data[{bit}])" if bit < 16 else
                     f".DI{bit}(1'b0)" for bit in range(18)]
            ports += [f".ADW{bit}(write_address[{bit}])" if bit < 6 else
                      f".ADW{bit}(1'b1)" for bit in range(9)]
            ports += [".BE0(1'b1)", ".BE1(1'b1)", ".CEW(write_enable && !rst)"]
        else:
            lines.append(f"    ) bank_{bank} (")
            ports = [f".DI{bit}(1'b0)" for bit in range(18)]
            ports += [f".ADW{bit}(1'b0)" for bit in range(9)]
            ports += [".BE0(1'b0)", ".BE1(1'b0)", ".CEW(1'b0)"]
        ports += [".CLKW(clk)", ".CSW0(1'b0)", ".CSW1(1'b0)", ".CSW2(1'b0)"]
        ports += [f".ADR{bit}(address[{bit - 4}])" if bit >= 4 else
                  f".ADR{bit}(1'b0)" for bit in range(13)]
        ports += [".CER(enable)", ".OCER(1'b1)", ".CLKR(clk)", ".RST(rst)",
                  ".CSR0(1'b0)", ".CSR1(1'b0)", ".CSR2(1'b0)"]
        ports += [f".DO{bit}(raw_{bank}[{bit}])" for bit in range(18)]
        lines.append("        " + ",\n        ".join(ports))
        lines.append("    );")
    lines += ["    always @* begin", "        case (bank)"]
    for bank in range(banks):
        lines.append(f"        3'd{bank}: data = {{raw_{bank}[6:0], raw_{bank}[17:9]}};")
    lines += ["        default: data = 16'h00b0;",
              "        endcase", "    end", "endmodule", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("binary", type=Path)
    parser.add_argument("--words", type=int, required=True)
    parser.add_argument("--format", choices=("verilog", "mem"), default="verilog")
    parser.add_argument("--module-name", default="j11_urom_ebr")
    args = parser.parse_args()
    try:
        binary = args.binary.read_bytes()
        output = (generate(binary, args.words, args.module_name)
                  if args.format == "verilog" else generate_mem(binary, args.words))
        print(output, end="")
    except (OSError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
