#!/usr/bin/env python3
"""Generate and run microcpu arithmetic benchmarks."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
from dataclasses import dataclass


STAT_RE = re.compile(r"microemu: stats: steps=(\d+) cycles=(\d+)")


@dataclass(frozen=True)
class Benchmark:
    name: str
    library: str
    setup: str
    op: str
    iterations: int


@dataclass(frozen=True)
class Result:
    steps: int
    cycles: int


INT32_SETUP = """\
\tset\tv0, $5678
\tset\tv1, $1234
\tset\tv2, $1111
\tset\tv3, $0001"""

INT32_SHIFT_SETUP = """\
\tset\tv0, $5678
\tset\tv1, $9234
\tset\tv2, 5
\tset\tv3, 0"""

FIS16_SETUP = """\
\tset\tv0, $c000
\tset\tv1, $0081
\tset\tv2, $8000
\tset\tv3, $0081"""

FIS32_SETUP = """\
\tset\tv0, 0
\tset\tv1, $4140
\tset\tv2, 0
\tset\tv3, $4100"""


BENCHMARKS = [
    Benchmark("int32.add", "int32", INT32_SETUP,
              "\tbsr\ti32_add", 512),
    Benchmark("int32.sub", "int32", INT32_SETUP,
              "\tbsr\ti32_sub", 512),
    Benchmark("int32.mul", "int32", INT32_SETUP,
              "\tbsr\ti32_mul", 128),
    Benchmark("int32.div", "int32", INT32_SETUP,
              "\tbsr\ti32_div", 64),
    Benchmark("int32.shl", "int32", INT32_SHIFT_SETUP,
              "\tbsr\tu32_shl", 512),
    Benchmark("int32.shr", "int32", INT32_SHIFT_SETUP,
              "\tbsr\tu32_shr", 512),
    Benchmark("int32.sar", "int32", INT32_SHIFT_SETUP,
              "\tbsr\ti32_sar", 512),
    Benchmark("fis16.add", "fis16", FIS16_SETUP,
              "\tjsr\tfadd", 256),
    Benchmark("fis16.sub", "fis16", FIS16_SETUP,
              "\tjsr\tfsub", 256),
    Benchmark("fis16.mul", "fis16", FIS16_SETUP,
              "\tjsr\tfmul", 128),
    Benchmark("fis16.div", "fis16", FIS16_SETUP,
              "\tjsr\tfdiv", 64),
    Benchmark("fis32.add", "fis32", FIS32_SETUP,
              "\tjsr\tf32add", 128),
    Benchmark("fis32.sub", "fis32", FIS32_SETUP,
              "\tjsr\tf32sub", 128),
    Benchmark("fis32.mul", "fis32", FIS32_SETUP,
              "\tjsr\tf32mul", 64),
    Benchmark("fis32.div", "fis32", FIS32_SETUP,
              "\tjsr\tf32div", 32),
]


def repo_root() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parents[2]


def expanded_library(root: pathlib.Path, library: str) -> str:
    include_dir = root / "asm" / "include"
    int32 = (include_dir / "int32.inc").read_text(encoding="utf-8")
    if library == "int32":
        return int32
    if library == "fis16":
        fis = (include_dir / "fis.inc").read_text(encoding="utf-8")
        return fis.replace("include int32.inc", int32)
    if library == "fis32":
        fis32 = (include_dir / "fis32.inc").read_text(encoding="utf-8")
        return fis32.replace("include int32.inc", int32)
    raise ValueError(f"unknown library {library}")


def asm_source(root: pathlib.Path, bench: Benchmark, op_body: str) -> str:
    pseudo = (root / "asm" / "include" / "pseudo.inc").read_text(encoding="utf-8")
    library = expanded_library(root, bench.library)
    return f""";
; Generated by microemu/scripts/bench_ops.py.
;

{pseudo}

org $0000

ITER_COUNT equ {bench.iterations}

\tset\tsp, runtime_stack
\tset\tv4, iter_count
\tset\tv0, ITER_COUNT
\tstr\tv0, v4, 0

bench_loop:
\tset\tv4, iter_count
\tldr\tv0, v4, 0
\teq\tv0, 0
\tb\tbench_body
\tb\tbench_done

bench_body:
{bench.setup}
{op_body}
\tset\tv4, sink
\tstr\tv0, v4, 0
\tstr\tv1, v4, 2

\tset\tv4, iter_count
\tldr\tv0, v4, 0
\tsub\tv0, v0, 1
\tstr\tv0, v4, 0
\tb\tbench_loop

bench_done:
\tb\t*

{library}

align 1

iter_count:
\tdw\t0
sink:
\tdw\t0, 0
\tds\t256
runtime_stack:
"""


def run_checked(cmd: list[str], *, cwd: pathlib.Path) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE, check=False)


def decode_output(data: bytes) -> str:
    return data.decode("utf-8", errors="replace")


def build_and_run(root: pathlib.Path, build_dir: pathlib.Path,
                  assembler: pathlib.Path, emulator: pathlib.Path,
                  name: str, bench: Benchmark, op_body: str) -> Result:
    source = build_dir / f"{name}.asm"
    binary = build_dir / f"{name}.bin"
    source.write_text(asm_source(root, bench, op_body), encoding="utf-8")

    asm_proc = run_checked([str(assembler), "-binary", str(source), str(binary)],
                           cwd=root)
    (build_dir / f"{name}.log").write_text(
        decode_output(asm_proc.stdout + asm_proc.stderr), encoding="utf-8")
    if asm_proc.returncode != 0:
        sys.stderr.write(decode_output(asm_proc.stdout))
        sys.stderr.write(decode_output(asm_proc.stderr))
        raise RuntimeError(f"assembler failed for {name}")

    emu_proc = run_checked([
        str(emulator),
        "--board", "hc1200-cpu",
        "--format", "bin",
        "--stop-on-self-branch",
        "--stats",
        "--max-steps", "100000000",
        str(binary),
    ], cwd=root)
    if emu_proc.returncode != 0:
        sys.stderr.write(decode_output(emu_proc.stdout))
        sys.stderr.write(decode_output(emu_proc.stderr))
        raise RuntimeError(f"emulator failed for {name}")

    stderr = decode_output(emu_proc.stderr)
    match = STAT_RE.search(stderr)
    if match is None:
        sys.stderr.write(decode_output(emu_proc.stdout))
        sys.stderr.write(stderr)
        raise RuntimeError(f"missing stats for {name}")
    return Result(steps=int(match.group(1)), cycles=int(match.group(2)))


def main() -> int:
    root = repo_root()
    parser = argparse.ArgumentParser(
        description="Run generated int32/FIS16/FIS32 microcpu benchmarks.")
    parser.add_argument("--build-dir", type=pathlib.Path,
                        default=root / "microemu" / "build" / "bench",
                        help="directory for generated benchmark sources")
    parser.add_argument("--assembler", type=pathlib.Path,
                        default=root / "asm" / "microasm",
                        help="microasm executable")
    parser.add_argument("--emulator", type=pathlib.Path,
                        default=root / "microemu" / "microemu",
                        help="microemu executable")
    args = parser.parse_args()

    args.build_dir.mkdir(parents=True, exist_ok=True)

    baselines: dict[tuple[str, str, int], Result] = {}
    rows: list[tuple[Benchmark, Result, Result]] = []
    for bench in BENCHMARKS:
        key = (bench.library, bench.setup, bench.iterations)
        if key not in baselines:
            baseline_name = f"baseline_{len(baselines)}"
            baselines[key] = build_and_run(
                root, args.build_dir, args.assembler, args.emulator,
                baseline_name, bench, "")
        result = build_and_run(root, args.build_dir, args.assembler,
                               args.emulator, bench.name.replace(".", "_"),
                               bench, bench.op)
        rows.append((bench, baselines[key], result))

    print("benchmark        iter   net steps/op   net cycles/op   total cycles")
    print("---------------  -----  ------------   -------------   ------------")
    for bench, baseline, result in rows:
        net_steps = (result.steps - baseline.steps) / bench.iterations
        net_cycles = (result.cycles - baseline.cycles) / bench.iterations
        print(f"{bench.name:<15}  {bench.iterations:>5}  "
              f"{net_steps:>12.2f}   {net_cycles:>13.2f}   "
              f"{result.cycles:>12}")
    print()
    print("Net values subtract the generated loop/setup baseline for the same operands.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
