/*
** Shared declarations for canonical Small-C split modules.
*/

#ifndef SMALLCC_GLOBALS_H
#define SMALLCC_GLOBALS_H

extern int
  nogo,
  noloc,
  opindex,
  opsize,
  swactive,
  swdefault,
 *swnext,
 *swend,
 *stage,
 *wq,
  argcs,
 *argvs,
 *wqptr,
  litptr,
  macptr,
  pptr,
  ch,
  nch,
  declared,
  iflevel,
  skiplevel,
  nxtlab,
  litlab,
  csp,
  argstk,
  argtop,
  ncmp,
  errflag,
  eof,
  output,
  files,
  filearg,
  input,
  input2,
  inclevel,
  incpath_count,
  skip_count,
  macro_param_count,
  include_open_count,
  objectmode,
  backend,
  pubclass,
  decltype2,
  functype,
  curtype,
  funcclass,
  usexpr,
  ccode,
 *snext,
 *stail,
 *slast,
  listfp,
  lastst,
  oldseg;

extern char
  optimize,
  alarm,
  monitor,
  pause,
 *symtab,
 *litq,
 *macn,
 *macq,
 *pline,
 *mline,
 *line,
 *lptr,
 *glbptr,
 *locptr,
  quote[2],
 *cptr,
 *cptr2,
 *cptr3,
  msname[MACNAMESIZE],
  ssname[NAMESIZE],
  typedef_name[MAXTYPEDEFS * NAMESIZE],
  struct_name[MAXSTRUCTS * NAMESIZE],
  field_name[MAXFIELDS * NAMESIZE],
  incpath[MAXINCPATHS * LINESIZE],
  incdir[(MAXINCLUDE + 1) * LINESIZE],
  macro_param_name[MAXMACPARAMS * MACNAMESIZE];

extern int
  typedef_count,
  typedef_type[MAXTYPEDEFS],
  typedef_id[MAXTYPEDEFS],
  typedef_size[MAXTYPEDEFS],
  struct_count,
  struct_size[MAXSTRUCTS],
  struct_first[MAXSTRUCTS],
  struct_fields[MAXSTRUCTS],
  field_count,
  field_parent[MAXFIELDS],
  field_type[MAXFIELDS],
  field_id[MAXFIELDS],
  field_size[MAXFIELDS],
  field_offset[MAXFIELDS],
  incfile[MAXINCLUDE],
  skip_arg[MAXSKIPARGS],
  macro_argc[MACNBR],
  macro_argfirst[MACNBR],
  op[16],
  op2[16];

int skipconst();
int doargs2();
int contline();

#endif
